### ISSUE TITLE
Modify Dark Reference File

### ISSUE THREAD

**Issue by tddesjardins** [spacetelescope/rad#291]
To support proper propagation of uncertainties from the dark subtraction, RTB would like to request the following changes to the dark reference file schema:

1. Add an array called "dark_slope" that is float32 and has Ndim = 2 with units of DN / second.
2. Change the "err" array to have Ndim = 2 (data type and units are fine as is). After discussion with @schlafly we are open to changing the name of this to be more descriptive as well. This should be the uncertainty in the slope estimate of the dark. Suggestions for the name are welcome in the comments, e.g., "dark_slope_err".

**Comment by schlafly** [comment]
RTB documentation is here: https://innerspace.stsci.edu/display/RI/Dark+Subtraction+-+v2
I vote for dark_slope_err, since we seem to use "err" preferenentially to "var" for reference files.  I don't think we should just do "err" since that would imply that this is the error on "data" rather than on the new dark_slope quantity.
