### ISSUE TITLE
Update science raw schema to include dq array

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/rad#304]
_Issue [RAD-132](https://jira.stsci.edu/browse/RAD-132) was created on JIRA by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis):_

We need to add the pixeldq array to the wfi_science_raw-1.0.0 schema.

SDF needs to fill in the "DROPOUT" value when some section of the data array cannot be filled if there is data loss.

We should add groupdq to the science raw files and have SDF only fill this in if there are data drops in the incoming telemetry.

**Comment by schlafly** [comment]
Sorry, thinking about this for the first time---when data loss occurs, is it for entire ramps or individual resultants within ramps?  I think I would have guessed the latter, in which case groupdq would be the name that better parallels the existing ramp schema, though we might also consider resultantdq, continuing to deprecate the word 'group' in favor of 'resultant.'

**Comment by schlafly** [comment]
@hcferguson , @nden , thinking about this more, I worry about the potential data volume concerns here; if we add a uint8 for every uint16 in the raw files, we'll be increasing the volume of the L1s by a factor of 1.5.  I think we've talked about wanting to compress streams in the asdf file, which would make this concern irrelevant, but I don't know if that's something that actually exists or if it's something we want to exist in the future.

If we don't yet have the capability to compress these, a somewhat more annoying approach would be to make the new column something like dropout_group_index = np.flatnonzero(groupdq), and store that.  That would presumably be an empty array for most images.  If we do think that lots of pixels will drop out we'd need to come up with something smarter, though.

If we add this for the main data array, we'll presumably also need to add it for the amp33 array.  That would be something like groupdq_amp33.  The reference pixel correction scheme would probably need an update in order to support missing pixels in amp33, though I suspect that's a minor change.

**Comment by hcferguson** [comment]
If there are dropouts, do we even have enough info to construct a partial array --- and even if so, is the dropout rate likely to be high enough that we would care? If not, I'd be inclined to just have a dq value for each read in the metadata.

**Comment by schlafly** [comment]
Good, yes, an optional groupdq array that is almost always absent makes sense.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-132?focusedCommentId=667334#comment-667334):_

This is implemented in RAD PR-328: #328

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-132?focusedCommentId=667364#comment-667364):_

PR approved and merged.
